name: redsticks

channels:
  - conda-forge

dependencies:
  - python=3.12

  # CLI
  - click
  - rich

  # Image / numerical processing
  - pillow
  - numpy

  # MediaPipe native runtime
  - libgl
  - libegl
  - libgles

  # Chemistry
  - rdkit

  # Native C++ extension
  - pybind11
  - cmake
  - ninja

  - pip
  - pip:
      - mediapipe
      - cloudsmith-cli==1.26.0
      - pytest