name: redsticks-demo
channels:
  - conda-forge
dependencies:
  - python=3.12
  - click
  - rdkit
  - pillow
  - rich
  - numpy
  - pytorch
  - torchvision
  - transformers
  - huggingface_hub
  - pybind11
  - cmake
  - ninja
  - pip
  - pip:
      - cloudsmith-cli==1.26.0
      - pytest
